function [numCamps,mbHours,obHours,mbTrips,obTrips,totalTrips,optimalTripsTotal,occPer,iterationCounts] = dfReadAndMedian(fileName)
    [numCamps,mbHours,obHours,mbTrips,obTrips,totalTrips,optimalTripsTotal,occPer,iterationCounts] = dfRead(fileName);
    numCamps = reshapeAndMedian(numCamps,iterationCounts);
    mbHours = reshapeAndMedian(mbHours,iterationCounts);
    obHours = reshapeAndMedian(obHours,iterationCounts);
    mbTrips = reshapeAndMedian(mbTrips,iterationCounts);
    obTrips = reshapeAndMedian(obTrips,iterationCounts);
    totalTrips = reshapeAndMedian(totalTrips,iterationCounts);
    optimalTripsTotal = reshapeAndMedian(optimalTripsTotal,iterationCounts);
    occPer = reshapeAndMedian(occPer,iterationCounts);